#!/usr/bin/env python3
# Spec-only test runner for mutation testing.  Includes ONLY tests whose
# expected values were derived independently from spec/first principles --
# excludes the seven packet-file regression tests AND all gray-zone tests whose
# expected values may have been frozen from loopdata output.
import sys, unittest
import test_process_packet as T

SPEC_TESTS = [
    'test_parse_cname',
    'test_compose_loop_data_dir',
    'test_compose_ssh_options',
    'test_period_classification',
    'test_get_windrun_bucket',
    'test_massage_near_zero',
    'test_construct_baro_trend_descs',
    'test_compute_period_obstypes',
    'test_compute_period_obstypes_isolated_composites',
    'test_get_fields_to_include',
    'test_parse_almanac_field',
    'test_get_almanac_fields',
    'test_almanac_field_evaluator',
    'test_almanac_no_data_not_cached',
    'test_almanac_next_group_expires_at_event',
    'test_almanac_next_group_no_data_retries',
    'test_almanac_next_group_timeless_day_roll',
    'test_almanac_previous_event_day_rolls',
    'test_almanac_unit_segment',
    'test_almanac_autocall_parity',
    'test_almanac_field_end_to_end',
    'test_almanac_texts_kwargs_match_weewx_signature',
    'test_parse_station_field',
    'test_get_station_fields',
    'test_station_field_evaluator',
    'test_station_field_autocall_parity',
    'test_get_barometer_trend_mbar',
    'test_get_barometer_trend_inHg',
    'test_get_trend_computation',
    'test_add_trend_obstype_barometer_code_desc',
    'test_prune_period_packet',
    'test_day_wind_vecdir_vecavg',
    'test_continuous_wind_vecdir_expiry',
    'test_min_max_dict',
    'test_continuous_scalar_stats_edge_cases',
    'test_continuous_vec_stats_edge_cases',
    'test_continuous_vec_stats_trim_debits_every_field',
    'test_continuous_vec_stats_trim_boundary_and_calm',
    'test_continuous_vec_stats_getstatstuple_and_accessors',
    'test_continuous_vec_stats_addsum_credits',
    'test_continuous_scalar_stats_sums_and_trim',
    'test_add_period_obstype_scalar_agg_dispatch',
    'test_agg_type_grammar_is_dispatch_union',
    'test_agg_extractors_reference_real_slots',
    'test_add_current_obstype_format_spec_dispatch',
    'test_create_loopdata_packet_period_routing',
    'test_unit_override_current',
    'test_unit_override_period',
    'test_time_context_formatting',
    'test_unit_override_trend_offset_unit',
    'test_parse_call_spec',
    'test_call_spec_rendering_parity',
    'test_almanac_call_spec',
    'test_add_period_obstype_vec_agg_dispatch',
    'test_continuous_firstlast_accum_basic',
    'test_continuous_accum_units_and_wind',
    'test_continuous_vec_ysum_separation',
    'test_continuous_vec_dir_wraparound_and_zero_vector',
    'test_get_trend_guard_branches',
    'test_day_wind_vecdir_loop_vs_quantized_archive',
    'test_create_period_accum_from_database',
    'test_create_period_accum_empty_obstypes',
    'test_create_period_accum_day_summary_upper_bound',
    'test_continuous_firstlast_accum_empty',
    'test_firstlast_obstype_end_to_end',
    'test_period_accum_wrappers_distinct_spans',
    'test_period_accum_wrappers_use_correct_spans',
    'test_create_hour_accum_from_database',
    'test_create_continuous_accum_from_database',
    'test_windrose_banding',
    'test_parse_windrose_bands',
    'test_get_windrose_periods',
    'test_windrose_span_accum',
    'test_windrose_continuous_accum',
    'test_windrose_seed_from_database',
    'test_windrose_end_to_end',
    'test_i18n_en_conf_ships_exactly_what_renders',
    'test_i18n_javascript_lookups_match_the_t_feed',
    'test_skin_palette_kept_in_step',
    'test_i18n_lang_files_consistent',
    'test_i18n_de_conf_is_complete',
    'test_i18n_fr_conf_is_complete',
    'test_i18n_nl_conf_is_complete',
    'test_i18n_es_conf_is_complete',
    'test_i18n_da_conf_is_complete',
    'test_i18n_it_conf_is_complete',
    'test_i18n_no_conf_is_complete',
    'test_i18n_sv_conf_is_complete',
    'test_i18n_lang_files_in_step_with_siblings',
    # Manual/code lockstep audits: these read repo sources (the docs, the
    # installer, skin.conf, changes.txt) and compare them against the code's
    # own tables -- never against loopdata output -- so they are spec-derived.
    'test_manual_heading_slug_rule',
    'test_manual_internal_links_and_anchors_resolve',
    'test_manual_page_furniture',
    'test_published_manual_urls_are_not_trailing_slash',
    'test_manual_theme_is_pinned_and_uncredited',
    'test_manual_documents_every_config_option',
    'test_manual_sample_config_matches_the_installer',
    'test_manual_field_grammar_matches_the_code',
    'test_manual_almanac_cache_tiers_match_the_code',
    'test_manual_documents_every_skin_extra',
    'test_manual_language_list_matches_the_shipped_lang_files',
    'test_manual_windrose_defaults_match_the_code',
    'test_station_fields_page_lists_the_real_station_surface',
    'test_troubleshooting_documents_every_logged_error',
    'test_troubleshooting_invents_no_log_messages',
    'test_version_is_in_lockstep',
    'test_normalize_fields',
    'test_declared_fields_from_skin_dict',
    'test_declaration_merges_like_a_report',
    'test_enabled_reports',
    'test_unrecognized_field_is_reported',
    'test_trend_accumulators_keyed_by_window',
    'test_per_report_rendering_off_shared_accumulators',
    'test_legacy_flat_beside_report_keys',
    'test_windrose_accumulators_keyed_by_bands',
    'test_almanac_evaluators_are_per_report',
    'test_sample_skin_declares_what_the_manual_says',
    'test_windrose_bands_resolution',
    'test_defaults_unit_follows_stdreport_however_it_is_written',
    'test_unit_label_windrose_is_not_a_rose',
    'test_shared_windrose_edges_builds_the_converter_only_on_a_miss',
    'test_shim_builds_each_evaluator_independently',
    'test_init_wires_the_contexts',
    # The installer's own stanza: that it arrives commented, that the
    # comments survive weecfg's conditional_merge, and the values it
    # writes on a fresh install.
    'test_installer_stanza_is_commented',
    'test_installer_commented_defaults',
    'test_installer_commented_defaults_match_the_value_that_governs',
    'test_installer_comment_blocks_land_where_they_are_written',
    'test_installer_merged_comments_stay_in_their_section',
    'test_installer_comments_survive_the_merge',
    'test_installer_defaults',
    'test_shipped_skins_exist_and_scriptdata_generates_nothing',
    'test_finish_migration_reports_then_applies',
    'test_finish_migration_leaves_the_reports_own_bands_alone',
    'test_finish_migration_does_not_move_the_file',
    'test_finish_migration_still_has_work_when_the_line_is_gone',
    'test_legacy_bands_follow_the_target_report',
    'test_a_failing_report_does_not_stop_the_file',
    'test_legacy_fields_are_shared_with_any_matching_report',
    'test_version_tuple_is_shared_with_the_installer',
    'test_service_init_leaves_no_temp_file',
]

suite = unittest.TestSuite([T.ProcessPacketTests(name) for name in SPEC_TESTS])
result = unittest.TextTestRunner(verbosity=0).run(suite)
sys.exit(0 if result.wasSuccessful() else 1)
